name = "Julia4STS"
uuid = "b89b6f60-96e7-4220-b7ab-434d4993e3e3"
authors = ["Lorenzo Campoli"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
